<script lang="ts">
	import { Chart, Card, A, Button, Dropdown, DropdownItem, Popover } from 'flowbite-svelte';
	import {
		InfoCircleSolid,
		ChevronDownOutline,
		ChevronRightOutline,
		PenSolid,
		DownloadSolid,
		ShareNodesSolid,
		TrashBinSolid,
		DotsHorizontalOutline
	} from 'flowbite-svelte-icons';

	export let id = "PieChart";
	export let title = 'Credits';
	export let description = "Credits of this category completed...";
	export let series = [50, 50];
	export let labels = ['Credits Completed', 'Credits Remaining'];

	const options = {
		series: series,
		colors: ['#EFC40A', '#D6D6D6'],

		chart: {
			height: 420,
			width: '100%',
			type: 'pie'
		},
		stroke: {
			colors: ['white'],
			lineCap: ''
		},
		plotOptions: {
			pie: {
				labels: {
					show: true
				},
				size: '100%',
				dataLabels: {
					offset: -25
				}
			}
		},

		labels: labels,

		dataLabels: {
			enabled: true,
			style: {
				fontFamily: 'Inter, sans-serif'
			}
		},
		legend: {
			position: 'bottom',
			fontFamily: 'Inter, sans-serif'
		},
		yaxis: {
			labels: {
				formatter: function (value: number) {
					return value + '%';
				}
			}
		},
		xaxis: {
			labels: {
				formatter: function (value: number) {
					return value + '%';
				}
			},
			axisTicks: {
				show: false
			},
			axisBorder: {
				show: false
			}
		}
	};
</script>

<div class="flex w-full items-start justify-center">
	<div class="flex-col items-center">
		<div class="mb-1 flex items-center">
			<h5 class="me-1 text-xl font-bold leading-none text-gray-900">{title}</h5>
			<InfoCircleSolid
				id="pie1"
				class="ms-1 h-3.5 w-3.5 cursor-pointer text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-white"
			/>
			<Popover
				triggeredBy="#pie1"
				class="z-10 w-72 rounded-lg border border-gray-200 bg-white text-sm text-gray-500 shadow-sm dark:border-gray-600 dark:bg-white dark:text-gray-400"
				placement="bottom-start"
			>
				<div class="space-y-2 p-3">
					<h3 class="font-semibold text-gray-900 dark:text-white">Activity growth - Incremental</h3>
					<p>
						Report helps navigate cumulative growth of community activities. Ideally, the chart
						should have a growing trend, as stagnating chart signifies a significant decrease of
						community activity.
					</p>
					<h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
					<p>
						For each date bucket, the all-time volume of activities is calculated. This means that
						activities in period n contain all activities up to period n, plus the activities
						generated by your community in period.
					</p>
					<A href="/">Read more <ChevronRightOutline class="ms-1.5 h-2 w-2" /></A>
				</div>
			</Popover>
		</div>
	</div>
</div>

<Chart {options} class="h-full py-6" />
